version: '3.7'
services:
  api:
    container_name: nestjs
    image: nestjs-dev
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    ports:
      - 8082:8082
      - 3000:3000
    networks:
      - nest
    depends_on:
      - postgres
    command: npm run start:dev
  postgres:
    image: postgres:13-alpine
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - nest
volumes:
  postgres:
    name: nest-docker-db
networks:
  nest:
